name: plezy
description: "A beautiful Plex client for Flutter"
publish_to: "none"
version: 1.21.3+48

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.4.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http: ^1.2.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  window_manager: ^0.5.1
  logger: ^2.0.2
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  provider: ^6.1.2
  flex_color_picker: ^3.6.0
  qr_flutter: ^4.1.0
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  duration: ^4.0.3
  connectivity_plus: ^7.0.0
  os_media_controls:
    git:
      url: https://github.com/edde746/os-media-controls
      ref: 467251821f76bba37ed4c6d5ee1c9de27c285e34
  rate_limiter: ^1.0.0
  wakelock_plus:
    git:
      url: https://github.com/edde746/wakelock_plus
      path: wakelock_plus
  path_provider: ^2.1.0
  path: ^1.9.0
  universal_gamepad: ^1.5.0
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.41
  workmanager: ^0.9.0+3
  crypto: ^3.0.7
  file_picker: ^10.3.10
  saf_util: ^0.11.0
  saf_stream: ^0.12.2
  material_symbols_icons: ^4.2892.0
  web_socket_channel: ^3.0.1
  in_app_review: ^2.0.11
  dart_discord_presence: ^1.1.0
  flutter_svg: ^2.2.3
  mobile_scanner: ^6.0.2
  android_intent_plus: ^5.0.2
  background_downloader: ^9.5.2
  auto_updater:
    git:
      url: https://github.com/edde746/auto_updater
      path: packages/auto_updater

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  slang_build_runner: ^4.12.0
  dart_code_linter: ^3.2.1
  drift_dev: ^2.14.0

dependency_overrides:
  auto_updater_windows:
    git:
      url: https://github.com/edde746/auto_updater
      path: packages/auto_updater_windows

flutter:
  uses-material-design: true
  assets:
    - lib/data/iso_639_codes.json
    - assets/plezy.png
    - assets/plezy_adaptive_foreground.svg
    - assets/go-noto-current-regular.ttf
    - assets/shaders/nvscaler/
    - assets/shaders/anime4k/
    - assets/player_icons/
    - assets/rating_icons/
